version: '3.4'

services:
  sql-data:
    environment:
      SA_PASSWORD: 123456Abc
      ACCEPT_EULA: Y
    ports:
      - '14330:1433'
    volumes:
      - noceiling-sqldata:/var/opt/mssql

  text-snippet-api:
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${NOCEILING_TEXTSNIPPET_DB:-Server=sql-data;Database=NoCeiling.Services.TextSnippetDb;User Id=sa;Password=123456Abc}
    ports: 
      - "5001:80"

  text-snippet-webspa:
    ports: 
      - "4001:80"

volumes:
  noceiling-sqldata:
    external: false
