version: "3.4"

services: 
    sql-data:
        image: mcr.microsoft.com/mssql/server:2019-latest
    
    text-snippet-api:
        image: ${REGISTRY:-duc01226}/text-snippet-api:${PLATFORM:-linux}-${TAG:-latest}
        build: 
            context: .
            dockerfile: Services/NoCeiling.Duc.Interview.Test.TextSnippet.Api/Dockerfile
        depends_on: 
            - sql-data
    
    text-snippet-webspa:
        image: ${REGISTRY:-duc01226}/text-snippet-webspa:${PLATFORM:-linux}-${TAG:-latest}
        build:
            context: Web
            dockerfile: apps/text-snippet/Dockerfile
        depends_on:
            - text-snippet-api
    